DROP TABLE  IF EXISTS `privileges` ;


CREATE TABLE IF NOT EXISTS `privileges` (
  `pk_privilege` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `module` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`pk_privilege`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=134 ;

INSERT INTO `privileges` (`pk_privilege`, `name`, `description`, `module`) VALUES
(1, 'CATEGORY_ADMIN', 'Listado de secciones', 'CATEGORY'),
(2, 'CATEGORY_AVAILABLE', 'Aprobar SecciÃ³n', 'CATEGORY'),
(3, 'CATEGORY_UPDATE', 'Modificar SecciÃ³n', 'CATEGORY'),
(4, 'CATEGORY_DELETE', 'Eliminar SecciÃ³n', 'CATEGORY'),
(5, 'CATEGORY_CREATE', 'Crear SecciÃ³n', 'CATEGORY'),
(6, 'ARTICLE_ADMIN', 'Listados de ArtÃ­culos', 'ARTICLE'),
(7, 'ARTICLE_FRONTPAGE', 'AdministraciÃ³n de portadas', 'ARTICLE'),
(8, 'ARTICLE_PENDINGS', 'Listar noticias pendientes', 'ARTICLE'),
(9, 'ARTICLE_AVAILABLE', 'Aprobar Noticia', 'ARTICLE'),
(10, 'ARTICLE_UPDATE', 'Modificar ArtÃ­culo', 'ARTICLE'),
(11, 'ARTICLE_DELETE', 'Eliminar ArtÃ­culo', 'ARTICLE'),
(12, 'ARTICLE_CREATE', 'Crear ArtÃ­culo', 'ARTICLE'),
(13, 'ARTICLE_ARCHIVE', 'Recuperar/Archivar ArtÃ­culos de/a hemeroteca', 'ARTICLE'),
(14, 'ARTICLE_CLONE', 'Clonar ArtÃ­culo', 'ARTICLE'),
(15, 'ARTICLE_HOME', 'GestiÃ³n portada Home de artÃ­culos', 'ARTICLE'),
(16, 'ARTICLE_TRASH', 'gestiÃ³n papelera ArtÃ­culo', 'ARTICLE'),
(17, 'ARTICLE_ARCHIVE_ADMIN', 'Listado de hemeroteca', 'ARTICLE'),
(18, 'ADVERTISEMENT_ADMIN', 'Listado de  publicidad', 'ADVERTISEMENT'),
(19, 'ADVERTISEMENT_AVAILABLE', 'Aprobar publicidad', 'ADVERTISEMENT'),
(20, 'ADVERTISEMENT_UPDATE', 'Modificar publicidad', 'ADVERTISEMENT'),
(21, 'ADVERTISEMENT_DELETE', 'Eliminar publicidad', 'ADVERTISEMENT'),
(22, 'ADVERTISEMENT_CREATE', 'Crear publicidad', 'ADVERTISEMENT'),
(23, 'ADVERTISEMENT_TRASH', 'gestiÃ³n papelera publicidad', 'ADVERTISEMENT'),
(24, 'ADVERTISEMENT_HOME', 'gestiÃ³n de publicidad en Home', 'ADVERTISEMENT'),

(26, 'OPINION_ADMIN', 'Listado de  opiniÃ³n', 'OPINION'),
(27, 'OPINION_FRONTPAGE', 'Portada Opinion', 'OPINION'),
(28, 'OPINION_AVAILABLE', 'Aprobar OpiniÃ³n', 'OPINION'),
(29, 'OPINION_UPDATE', 'Modificar OpiniÃ³n', 'OPINION'),
(30, 'OPINION_HOME', 'Publicar widgets home OpiniÃ³n', 'OPINION'),
(31, 'OPINION_DELETE', 'Eliminar OpiniÃ³n', 'OPINION'),
(32, 'OPINION_CREATE', 'Crear OpiniÃ³n', 'OPINION'),
(33, 'OPINION_TRASH', 'gestion papelera OpiniÃ³n', 'OPINION'),
(34, 'COMMENT_ADMIN', 'Listado de comentarios', 'COMMENT'),
(35, 'COMMENT_POLL', 'Gestionar Comentarios de encuestas', 'COMMENT'),
(36, 'COMMENT_HOME', 'Gestionar Comentarios de Home', 'COMMENT'),
(37, 'COMMENT_AVAILABLE', 'Aprobar/Rechazar Comentario', 'COMMENT'),
(38, 'COMMENT_UPDATE', 'Modificar Comentario', 'COMMENT'),
(39, 'COMMENT_DELETE', 'Eliminar Comentario', 'COMMENT'),
(40, 'COMMENT_CREATE', 'Crear Comentario', 'COMMENT'),
(41, 'COMMENT_TRASH', 'gestiÃ³n papelera Comentarios', 'COMMENT'),
(42, 'ALBUM_ADMIN', 'Listado de Ã¡lbumes', 'ALBUM'),
(43, 'ALBUM_AVAILABLE', 'Aprobar Album', 'ALBUM'),
(44, 'ALBUM_UPDATE', 'Modificar Album', 'ALBUM'),
(45, 'ALBUM_DELETE', 'Eliminar Album', 'ALBUM'),
(46, 'ALBUM_CREATE', 'Crear Album', 'ALBUM'),
(47, 'ALBUM_TRASH', 'gestion papelera Album', 'ALBUM'),
(48, 'VIDEO_ADMIN', 'Listado de videos', 'VIDEO'),
(49, 'VIDEO_AVAILABLE', 'Aprobar video', 'VIDEO'),
(50, 'VIDEO_UPDATE', 'Modificar video', 'VIDEO'),
(51, 'VIDEO_DELETE', 'Eliminar video', 'VIDEO'),
(52, 'VIDEO_CREATE', 'Crear video', 'VIDEO'),
(53, 'VIDEO_TRASH', 'gestiÃ³n papelera video', 'VIDEO'),

(60, 'IMAGE_ADMIN', 'Listado de imÃ¡genes', 'IMAGE'),
(61, 'IMAGE_AVAILABLE', 'Aprobar Imagen', 'IMAGE'),
(62, 'IMAGE_UPDATE', 'Modificar Imagen', 'IMAGE'),
(63, 'IMAGE_DELETE', 'Eliminar Imagen', 'IMAGE'),
(64, 'IMAGE_CREATE', 'Subir Imagen', 'IMAGE'),
(65, 'IMAGE_TRASH', 'gestiÃ³n papelera Imagen', 'IMAGE'),
(66, 'STATIC_ADMIN', 'Listado pÃ¡ginas estÃ¡ticas', 'STATIC'),
(67, 'STATIC_AVAILABLE', 'Aprobar PÃ¡gina EstÃ¡tica', 'STATIC'),
(68, 'STATIC_UPDATE', 'Modificar PÃ¡gina EstÃ¡tica', 'STATIC'),
(69, 'STATIC_DELETE', 'Eliminar PÃ¡gina EstÃ¡tica', 'STATIC'),
(70, 'STATIC_CREATE', 'Crear PÃ¡gina EstÃ¡tica', 'STATIC'),
(71, 'KIOSKO_ADMIN', 'Listar PÃ¡gina Papel', 'KIOSKO'),
(72, 'KIOSKO_AVAILABLE', 'Aprobar PÃ¡gina Papel', 'KIOSKO'),
(73, 'KIOSKO_UPDATE', 'Modificar PÃ¡gina Papel', 'KIOSKO'),
(74, 'KIOSKO_DELETE', 'Eliminar PÃ¡gina Papel', 'KIOSKO'),
(75, 'KIOSKO_CREATE', 'Crear PÃ¡gina Papel', 'KIOSKO'),
(76, 'KIOSKO_HOME', 'Incluir en portada como favorito', 'KIOSKO'),
(77, 'POLL_ADMIN', 'Listado encuestas', 'POLL'),
(78, 'POLL_AVAILABLE', 'Aprobar Encuesta', 'POLL'),
(79, 'POLL_UPDATE', 'Modificar Encuesta', 'POLL'),
(80, 'POLL_DELETE', 'Eliminar Encuesta', 'POLL'),
(81, 'POLL_CREATE', 'Crear Encuesta', 'POLL'),
(82, 'AUTHOR_ADMIN', 'Listado autores OpiniÃ³n', 'AUTHOR'),
(83, 'AUTHOR_UPDATE', 'Modificar Autor', 'AUTHOR'),
(84, 'AUTHOR_DELETE', 'Eliminar Autor', 'AUTHOR'),
(85, 'AUTHOR_CREATE', 'Crear Autor', 'AUTHOR'),
(86, 'USER_ADMIN', 'Listado de usuarios', 'USER'),
(87, 'USER_UPDATE', 'Modificar Usuario', 'USER'),
(88, 'USER_DELETE', 'Eliminar Usuario', 'USER'),
(89, 'USER_CREATE', 'Crear Usuario', 'USER'),
(90, 'PCLAVE_ADMIN', 'Listado de palabras clave', 'PCLAVE'),
(91, 'PCLAVE_UPDATE', 'Modificar Palabra Clave', 'PCLAVE'),
(92, 'PCLAVE_DELETE', 'Eliminar Palabra Clave', 'PCLAVE'),
(93, 'PCLAVE_CREATE', 'Crear Palabra Clave', 'PCLAVE'),

(95, 'GROUP_ADMIN', 'Grupo usuarios Admin', 'GROUP'),
(96, 'GROUP_UPDATE', 'Modificar Grupo Usuarios', 'GROUP'),
(97, 'GROUP_DELETE', 'Eliminar Grupo Usuarios', 'GROUP'),
(98, 'GROUP_ADMIN', 'Listado de Grupo Usuarios', 'GROUP'),
(99, 'GROUP_CREATE', 'Crear Grupo Usuarios', 'GROUP'),
(100, 'PRIVILEGE_UPDATE', 'Modificar Privilegio', 'PRIVILEGE'),
(101, 'PRIVILEGE_DELETE', 'Eliminar Privilegio', 'PRIVILEGE'),
(102, 'PRIVILEGE_ADMIN', 'Listado de Privilegios', 'PRIVILEGE'),
(103, 'PRIVILEGE_CREATE', 'Crear Privilegio', 'PRIVILEGE'),
(104, 'FILE_ADMIN', 'Listado de ficheros y portadas', 'FILE'),
(105, 'FILE_FRONTS', 'GestiÃ³n de portadas', 'FILE'),
(106, 'FILE_UPDATE', 'Modificar Fichero', 'FILE'),
(107, 'FILE_DELETE', 'Eliminar Fichero', 'FILE'),
(108, 'FILE_CREATE', 'Crear Fichero', 'FILE'),
(109, 'MENU_CREATE', 'Crear menu', 'MENU'),
(110, 'BADLINK_ADMIN', 'Control Link Admin', 'BADLINK'),
(111, 'STATS_ADMIN', 'Admin EstadÃ­sticas', 'STATS'),
(112, 'NEWSLETTER_ADMIN', 'AdministraciÃ³n del boletÃ­n', 'NEWSLETTER'),
(113, 'BACKEND_ADMIN', 'ConfiguraciÃ³n de backend', 'BACKEND'),
(114, 'CACHE_TPL_ADMIN', 'GestiÃ³n de CachÃ©s Portadas', 'CACHE'),
(115, 'SEARCH_ADMIN', 'Utilidades: bÃºsqueda avanzada', 'SEARCH'),
(116, 'TRASH_ADMIN', 'GestiÃ³n papelera', 'TRASH'),
(117, 'WIDGET_ADMIN', 'Listado de widgets', 'WIDGET'),
(118, 'WIDGET_AVAILABLE', 'Aprobar Widget', 'WIDGET'),
(119, 'WIDGET_UPDATE', 'Modificar Widget', 'WIDGET'),
(120, 'WIDGET_DELETE', 'Eliminar Widget', 'WIDGET'),
(121, 'WIDGET_CREATE', 'Crear Widget', 'WIDGET'),
(122, 'MENU_ADMIN', 'Listado de menus', 'MENU'),
(123, 'MENU_AVAILABLE', 'Leer menu', 'MENU'),
(124, 'MENU_UPDATE', 'Modificar menu', 'MENU'),
(125, 'IMPORT_ADMIN', 'Listado de menus', 'IMPORT'),
(126, 'IMPORT_EPRESS', 'Leer Widget', 'IMPORT'),
(127, 'IMPORT_XML', 'Modificar Widget', 'IMPORT'),
(128, 'IMPORT_EFE', 'Eliminar Widget', 'IMPORT'),
(129, 'CACHE_APC_ADMIN', 'Gestion cache de APC', 'CACHE'),
(130, 'ONM_CONFIG', 'Configurar Onm', 'ONM'),
(131, 'ONM_MANAGER', 'Gestionar Onm', 'ONM'),
(132, 'CONTENT_OTHER_UPDATE', 'Poder modificar contenido de otros usuarios', 'CONTENT'),
(133, 'CONTENT_OTHER_DELETE', 'Poder eliminar contenido de otros usuarios', 'CONTENT'),
(134, 'ONM_SETTINGS', 'Allow to configure system wide settings', 'ONM'),
(135, 'GROUP_CHANGE', 'Cambiar de grupo al usuario ', 'GROUP'),
(136, 'USER_CATEGORY', 'Asignar categorias al usuario ', 'USER'),
(144, 'BOOK_TRASH', 'Vaciar papelera de libros', 'BOOK'),
(143, 'BOOK_DELETE', 'Eliminar libros', 'BOOK'),
(142, 'BOOK_UPDATE', 'Modificar libros', 'BOOK'),
(141, 'BOOK_SETTINGS', 'Configurar modulo de libros', 'BOOK'),
(140, 'BOOK_AVAILABLE', 'Aprobar libros', 'BOOK'),
(139, 'BOOK_FAVORITE', 'Gestionar Widget de libros', 'BOOK'),
(138, 'BOOK_CREATE', 'Subir libros', 'BOOK'),
(137, 'BOOK_ADMIN', 'Administrar modulo de libros', 'BOOK'),
(152, 'SPECIAL_TRASH', 'Gestionar papelera especiales', 'SPECIAL'),
(151, 'SPECIAL_DELETE', 'Eliminar especiales', 'SPECIAL'),
(150, 'SPECIAL_UPDATE', 'Modificar especiales', 'SPECIAL'),
(149, 'SPECIAL_SETTINGS', 'Configurar modulo de especiales', 'SPECIAL'),
(148, 'SPECIAL_AVAILABLE', 'Aprobar especiales', 'SPECIAL'),
(147, 'SPECIAL_FAVORITE', 'Gestionar widget especiales', 'SPECIAL'),
(146, 'SPECIAL_CREATE', 'Crear especiales', 'SPECIAL'),
(145, 'SPECIAL_ADMIN', 'Administrar modulo de especiales ', 'SPECIAL'),
(153, 'SCHEDULE_SETTINGS', 'Gestionar la agenda ', 'SCHEDULE'),
(154, 'SCHEDULE_ADMIN', 'Gestionar la agenda ', 'SCHEDULE'),
(155, 'CATEGORY_SETTINGS', 'Cambiar config de secciones', 'CATEGORY'),
(156, 'ALBUM_SETTINGS', 'Cambiar config de album', 'ALBUM'),
(157, 'VIDEO_SETTINGS', 'Cambiar config de video', 'VIDEO'),
(158, 'OPINION_SETTINGS', 'Cambiar config de opinion', 'OPINION');



