<?php
// Onm advertisement php file

return array_map(function ($ad) {
    $adObject = new Advertisement();
    foreach ($ad as $key => $value) {
        $adObject->{$key} = $value;
    }
    $adObject->default_ad = 1;
    return $adObject;
}, [
    0 => [
        'map' => null,
        'pk_advertisement' => '157',
        'type_advertisement' => '1',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-728x90 Leaderboard -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="2721775077"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '157',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top left leaderboard - Frontpage - 728x90 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'top,left,leaderboard,frontpage,728x90,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:44:24',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:44:24',
        'changed' => '2015-08-14 16:00:55',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-portada-top-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '157',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '157',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    2 => [
        'map' => null,
        'pk_advertisement' => '128',
        'type_advertisement' => '2',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '126',
        'path' => '126',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<a target="_blank" href="https://www.opennemas.com/es/registro?utm_source=Opennemas_free&utm_medium=banner&utm_term=free_newspapers&utm_content=234x90&utm_campaign=periodico_gratuito" rel="nofollow"><img alt="" src="/assets/images/advertisement/static/onm_ad234x90.jpg" width="234" height="90"></a>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '128',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top right leaderboard - Frontpage - 234x90 - Openhost Ads - Static',
        'description' => '',
        'body' => '',
        'metadata' => 'top,right,leaderboard,frontpage,234x90,openhost,ads,static',
        'starttime' => '2011-09-28 23:14:50',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:14:50',
        'changed' => '2013-04-18 09:42:56',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-portada-top-right',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '128',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '128',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    3 => [
        'map' => null,
        'pk_advertisement' => '133',
        'type_advertisement' => '3',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'728x90 (728x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506851, rank:1, width:728, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506851&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'728\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'728x90 (728x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '133',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Center left leaderboard - Frontpage - 728x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'center,left,leaderboard,frontpage,728x90,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:19:44',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:19:44',
        'changed' => '2015-08-14 16:03:00',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-portada-middle-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '133',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '133',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    4 => [
        'map' => null,
        'pk_advertisement' => '135',
        'type_advertisement' => '4',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'234x90 (234x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51510546, rank:1, width:234, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51510546&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'234\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'234x90 (234x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '135',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Center rigth leaderboard - Frontpage - 234x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'center,rigth,leaderboard,frontpage,234x90,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:20:48',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:20:48',
        'changed' => '2015-08-14 16:04:51',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
            'openx_zone_id' => '',
            'googledfp_unit_id' => '',
        ],
        'slug' => 'publicidad-portada-middle-right',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '135',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '135',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    6 => [
        'map' => null,
        'pk_advertisement' => '242',
        'type_advertisement' => '5',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'728x90 (728x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506851, rank:1, width:728, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506851&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'728\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'728x90 (728x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '242',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom left leaderboard - Frontpage - 728x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom, left, leaderboard, frontpage, 728x90, openhost, ads, ikreate',
        'starttime' => '2015-08-14 00:00:00',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2015-08-21 18:01:45',
        'changed' => '2015-08-21 18:01:45',
        'fk_user' => '0',
        'fk_publisher' => '0',
        'fk_user_last_editor' => '0',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => 728,
            'height' => 90,
        ],
        'slug' => 'bottom-left-leaderboard-frontpage-728x90-openhost-ads-ikreate',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '242',
        'fk_content_type' => '2',
        'fk_author' => '0',
        'urn_source' => '',
        'pk_fk_content' => '242',
        'pk_fk_content_category' => '0',
        'catName' => '0',
    ],
    7 => [
        'map' => null,
        'pk_advertisement' => '131',
        'type_advertisement' => '6',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'234x90 (234x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51510546, rank:1, width:234, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51510546&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'234\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'234x90 (234x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '131',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom right Leaderboard - Frontpage - 234x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom,right,leaderboard,frontpage,234x90,openhost,ads',
        'starttime' => '2011-09-28 23:17:47',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:17:47',
        'changed' => '2015-08-14 16:09:15',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-portada-botton-right',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '131',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '131',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    8 => [
        'map' => null,
        'pk_advertisement' => '136',
        'type_advertisement' => '31',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '136',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos1 Col3 - Frontpage - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos2,col3,frontpage,300x250,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:23:16',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:23:16',
        'changed' => '2013-04-18 05:55:37',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-portada-columna3',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '136',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '136',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    9 => [
        'map' => null,
        'pk_advertisement' => '132',
        'type_advertisement' => '32',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '132',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos2 Col3 - Frontpage - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'publicidad, portada, columna1, adsense',
        'starttime' => '2011-09-28 23:19:00',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:19:00',
        'changed' => '2015-08-14 16:16:54',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-portada-columna1',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '132',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '132',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    11 => [
        'map' => null,
        'pk_advertisement' => '137',
        'type_advertisement' => '101',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-728x90 Leaderboard -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="2721775077"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '137',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top left leaderboard - Inner article - 728x90 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'top,left,leaderboard,frontpage,728x90,openhost,ads,inner,article,adsense',
        'starttime' => '2011-09-28 23:24:19',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:24:19',
        'changed' => '2015-08-14 16:25:37',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-inner-top-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '137',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '137',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    12 => [
        'map' => null,
        'pk_advertisement' => '132',
        'type_advertisement' => '33',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '132',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos3 Col3 - Frontpage - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'publicidad, portada, columna3, pos3, Ikreate',
        'starttime' => '2011-09-28 23:19:00',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:19:00',
        'changed' => '2015-08-14 16:16:54',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-portada-columna3-pos3',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '132',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '132',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    13 => [
        'map' => null,
        'pk_advertisement' => '138',
        'type_advertisement' => '102',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'234x90 (234x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51510546, rank:1, width:234, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51510546&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'234\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'234x90 (234x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '138',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top right leaderboard - Inner Article - 234x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'top,right,leaderboard,inner,article,234x90,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:25:19',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:25:19',
        'changed' => '2015-08-14 16:24:25',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-inner-top-right',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '138',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '138',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    14 => [
        'map' => null,
        'pk_advertisement' => '224',
        'type_advertisement' => '103',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '224',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos1 - Inner Article - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos1,inner,article,300x250,openhost,ads,adsense',
        'starttime' => '2011-10-18 01:14:09',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-10-18 01:14:09',
        'changed' => '2013-04-18 04:33:07',
        'fk_user' => '3',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-inner-top-right-columna1',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '224',
        'fk_content_type' => '2',
        'fk_author' => '3',
        'urn_source' => '',
        'pk_fk_content' => '224',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    15 => [
        'map' => null,
        'pk_advertisement' => '139',
        'type_advertisement' => '104',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-468x60-robapagina -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:468px;height:60px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="7755935294"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '139',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Full banner - Inner Article - 468x60 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'full,banner,inner,article,468x60,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:26:10',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:26:10',
        'changed' => '2015-08-14 16:30:22',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '468',
            'height' => '60',
        ],
        'slug' => 'publicidad-inner-robapage',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '139',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '139',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    16 => [
        'map' => null,
        'pk_advertisement' => '244',
        'type_advertisement' => '104',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'468x60 (468x60)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506852, rank:1, width:468, height:60, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506852&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'468\' height=\'60\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'468x60 (468x60)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '244',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Full banner - Inner Article - 468x60 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'full, banner, inner, article, 468x60, openhost, ads, ikreate',
        'starttime' => '2015-08-14 00:00:00',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2015-08-21 18:01:45',
        'changed' => '2015-08-21 18:01:45',
        'fk_user' => '0',
        'fk_publisher' => '0',
        'fk_user_last_editor' => '0',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => 468,
            'height' => 60,
        ],
        'slug' => 'full-banner-inner-article-468x60-openhost-ads-ikreate',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '244',
        'fk_content_type' => '2',
        'fk_author' => '0',
        'urn_source' => '',
        'pk_fk_content' => '244',
        'pk_fk_content_category' => '0',
        'catName' => '0',
    ],
    18 => [
        'map' => null,
        'pk_advertisement' => '156',
        'type_advertisement' => '109',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'728x90 (728x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506851, rank:1, width:728, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506851&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'728\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'728x90 (728x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '156',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom left leaderboard - Inner Article - 728x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom,left,leaderboard,inner,article,300x250,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:43:15',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:43:15',
        'changed' => '2015-08-14 16:35:53',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-inner-bottom-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '156',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '156',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    19 => [
        'map' => null,
        'pk_advertisement' => '134',
        'type_advertisement' => '110',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'234x90 (234x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51510546, rank:1, width:234, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51510546&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'234\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'234x90 (234x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '134',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom right leaderboard - Inner Article - 234x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom,right,leaderboard,inner,article,234x90,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:20:24',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:20:24',
        'changed' => '2015-08-14 16:38:11',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '7',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-portada-middle-right',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '134',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '134',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    20 => [
        'map' => null,
        'pk_advertisement' => '239',
        'type_advertisement' => '193',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-120x600-Skycraper -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:120px;height:600px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="2407405696"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '239',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Body skycraper - Inner Article - 120x600 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'body,skycraper,inner,article,120x600,openhost,ads,adsense',
        'starttime' => '2013-04-18 06:40:33',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2013-04-18 06:40:33',
        'changed' => '2015-08-14 16:41:55',
        'fk_user' => '4',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '4',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '120',
            'height' => '600',
        ],
        'slug' => 'body-skycraper-inner-article-120x600-openhost-ads',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '239',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '239',
        'pk_fk_content_category' => '0',
        'catName' => '0',
    ],
    22 => [
        'map' => null,
        'pk_advertisement' => '141',
        'type_advertisement' => '601',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-728x90 Leaderboard -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="2721775077"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '141',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top left leaderboard - Frontpage OPINION - 728x90 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'top,left,leaderboard,frontpage,opinion,728x90,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:28:18',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:28:18',
        'changed' => '2015-08-14 16:54:38',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-top-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '141',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '141',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    24 => [
        'map' => null,
        'pk_advertisement' => '143',
        'type_advertisement' => '602',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '126',
        'path' => '126',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<a target="_blank" href="https://www.opennemas.com/es/registro?utm_source=Opennemas_free&utm_medium=banner&utm_term=free_newspapers&utm_content=234x90&utm_campaign=periodico_gratuito" rel="nofollow"><img alt="" src="/assets/images/advertisement/static/onm_ad234x90.jpg" width="234" height="90"></a>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '143',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top right leaderboard - Opinion Frontpage - 234x90 - Openhost Ads - Static',
        'description' => '',
        'body' => '',
        'metadata' => 'top,right,leaderboard,opinion,frontpage,234x90,openhost,ads,static',
        'starttime' => '2011-09-28 23:29:47',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:29:47',
        'changed' => '2013-04-18 09:10:49',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-column',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '143',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '143',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    25 => [
        'map' => null,
        'pk_advertisement' => '149',
        'type_advertisement' => '603',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '149',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos1 - Opinion Frontpage - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos1,opinion,frontpage,300x250,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:34:30',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:34:30',
        'changed' => '2013-04-18 09:30:05',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-opinion-inner-columna',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '149',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '149',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    26 => [
        'map' => null,
        'pk_advertisement' => '144',
        'type_advertisement' => '605',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '144',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos2 - Opinion Frontpage - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos2,opinion,frontpage,300x250,openhost,ads',
        'starttime' => '2011-09-28 23:30:45',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:30:45',
        'changed' => '2015-08-14 16:58:00',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-opinion-column3',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '144',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '144',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    27 => [
        'map' => null,
        'pk_advertisement' => '145',
        'type_advertisement' => '609',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'728x90 (728x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506851, rank:1, width:728, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506851&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'728\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'728x90 (728x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '145',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom Left leaderboard - Opinion Frontpage - 728x90 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom,left,leaderboard,opinion,frontpage,728x90,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:31:31',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:31:31',
        'changed' => '2015-08-14 17:00:39',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-bottom-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '145',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '145',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    28 => [
        'map' => null,
        'pk_advertisement' => '146',
        'type_advertisement' => '610',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'234x90 (234x90)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51510546, rank:1, width:234, height:90, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51510546&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'234\' height=\'90\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'234x90 (234x90)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '146',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Bottom right leaderboard - Frontpage Opinion - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'bottom,right,leaderboard,frontpage,opinion,300x250,openhost,ads',
        'starttime' => '2011-09-28 23:32:19',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:32:19',
        'changed' => '2015-08-14 17:01:58',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-bottom-right',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '146',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '146',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    29 => [
        'map' => null,
        'pk_advertisement' => '148',
        'type_advertisement' => '701',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-728x90 Leaderboard -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="2721775077"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '148',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top left leaderboard - Inner Opinion - 728x90 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'top,left,leaderboard,inner,opinion,728x90,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:33:49',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:33:49',
        'changed' => '2015-08-14 17:02:54',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '728',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-inner-top-left',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '148',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '148',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    31 => [
        'map' => null,
        'pk_advertisement' => '147',
        'type_advertisement' => '702',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '126',
        'path' => '126',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<a target="_blank" href="https://www.opennemas.com/es/registro?utm_source=Opennemas_free&utm_medium=banner&utm_term=free_newspapers&utm_content=234x90&utm_campaign=periodico_gratuito" rel="nofollow"><img alt="" src="/assets/images/advertisement/static/onm_ad234x90.jpg" width="234" height="90"></a>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '147',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Top right leaderboard - Inner Opinion - 234x90 - Openhost Ads - Static',
        'description' => '',
        'body' => '',
        'metadata' => 'top,right,leaderboard,inner,opinion,234x90,openhost,ads,static',
        'starttime' => '2011-09-28 23:33:12',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:33:12',
        'changed' => '2013-04-18 06:10:14',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '234',
            'height' => '90',
        ],
        'slug' => 'publicidad-opinion-inner-top-right',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '147',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '147',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    32 => [
        'map' => null,
        'pk_advertisement' => '238',
        'type_advertisement' => '703',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-300x250 - Medium Rectangle - #1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:300px;height:250px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="9055006270"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '238',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos1 - Inner Opinion - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos1,inner,opinion,300x250,openhost,ads,adsense',
        'starttime' => '2013-04-18 06:05:41',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2013-04-18 06:05:41',
        'changed' => '2013-04-18 06:05:41',
        'fk_user' => '3',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '3',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'medium-rectangle-pos1-inner-opinion-300x250-openhost-ads',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '238',
        'fk_content_type' => '2',
        'fk_author' => '3',
        'urn_source' => '',
        'pk_fk_content' => '238',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    33 => [
        'map' => null,
        'pk_advertisement' => '159',
        'type_advertisement' => '705',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '159',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos2 - Inner Opinion - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos2,inner,opinion,300x250,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:48:57',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:48:57',
        'changed' => '2015-08-14 17:05:05',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-opinion-inner-column',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '159',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '159',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    34 => [
        'map' => null,
        'pk_advertisement' => '136',
        'type_advertisement' => '11',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '136',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos1 Col1 - Frontpage - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos1,col1,frontpage,300x250,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:23:16',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:23:16',
        'changed' => '2013-04-18 05:55:37',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-portada-columna1-pos1',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '136',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '136',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    35 => [
        'map' => null,
        'pk_advertisement' => '136',
        'type_advertisement' => '21',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '136',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos2 Col1 - Frontpage - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos2,col1,frontpage,300x250,openhost,ads,ikreate',
        'starttime' => '2011-09-28 23:23:16',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:23:16',
        'changed' => '2013-04-18 05:55:37',
        'fk_user' => '7',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-portada-columna2-pos1',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '136',
        'fk_content_type' => '2',
        'fk_author' => '7',
        'urn_source' => '',
        'pk_fk_content' => '136',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    37 => [
        'map' => null,
        'pk_advertisement' => '224',
        'type_advertisement' => '105',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '224',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos2 - Inner Article - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos2,inner,article,300x250,openhost,ads,ikreate',
        'starttime' => '2011-10-18 01:14:09',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-10-18 01:14:09',
        'changed' => '2013-04-18 04:33:07',
        'fk_user' => '3',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-inner-right-column-pos2',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '224',
        'fk_content_type' => '2',
        'fk_author' => '3',
        'urn_source' => '',
        'pk_fk_content' => '224',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    38 => [
        'map' => null,
        'pk_advertisement' => '224',
        'type_advertisement' => '106',
        'fk_content_categories' => [ 0 => '0' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '224',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos3 - Inner Article - 300x250 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos3,inner,article,300x250,openhost,ads,ikreate',
        'starttime' => '2011-10-18 01:14:09',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-10-18 01:14:09',
        'changed' => '2013-04-18 04:33:07',
        'fk_user' => '3',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '3',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-inner-right-column-pos3',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '224',
        'fk_content_type' => '2',
        'fk_author' => '3',
        'urn_source' => '',
        'pk_fk_content' => '224',
        'pk_fk_content_category' => '0',
        'catName' => '',
    ],
    47 => [
        'map' => null,
        'pk_advertisement' => '246',
        'type_advertisement' => '793',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'120x600 (120x600)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:51506850, rank:1, width:120, height:600, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=51506850&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'120\' height=\'600\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'120x600 (120x600)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '246',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Body skycraper - Inner Opinion - 120x600 - Openhost Ads - Ikreate',
        'description' => '',
        'body' => '',
        'metadata' => 'body, skycraper, inner, opinion, 120x600, openhost, ads, ikreate',
        'starttime' => '2015-08-14 00:00:00',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2015-08-21 18:01:46',
        'changed' => '2015-08-21 18:01:46',
        'fk_user' => '0',
        'fk_publisher' => '0',
        'fk_user_last_editor' => '0',
        'category' => '0',
        'category_name' => false,
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => 120,
            'height' => 600,
        ],
        'slug' => 'body-skycraper-inner-opinion-120x600-openhost-ads-ikreate',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '246',
        'fk_content_type' => '2',
        'fk_author' => '0',
        'urn_source' => '',
        'pk_fk_content' => '246',
        'pk_fk_content_category' => '0',
        'catName' => '0',
    ],
    48 => [
        'map' => null,
        'pk_advertisement' => '159',
        'type_advertisement' => '706',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<!-- START Admeta Placement Holder Web site: \'Openhost\', Web page \'http://opennemas.com/\', Format: \'300x250 (300x250)\' Priority: 1 START -->
            <script type=\'text/javascript\'>
              var ADM_PL = {tp:\'sp\', wId:599741, pId:7010263, rank:1, width:300, height:250, pbId:173, clk:\'[External click-tracking goes here (NOT URL-encoded)]\'};
            </script>
            <script type=\'text/javascript\' src=\'//s.atemda.com/Admeta.js\'></script>
            <noscript>
              <iframe src=\'//p173.atemda.com/nojsadserving.ashx?wId=599741&pId=7010263&rank=1&clk=[URL-encoded external clicktracking link goes here]\' width=\'300\' height=\'250\' frameborder=\'0\' marginheight=\'0\' marginwidth=\'0\' scrolling=\'no\'></iframe>
            </noscript>
            <!-- END End of Admeta Placement Holder \'300x250 (300x250)\' (1) END -->',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '159',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Medium Rectangle - Pos3 - Inner Opinion - 300x250 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'medium,rectangle,pos3,inner,opinion,300x250,openhost,ads,adsense',
        'starttime' => '2011-09-28 23:48:57',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2011-09-28 23:48:57',
        'changed' => '2015-08-14 17:05:05',
        'fk_user' => '4',
        'fk_publisher' => '7',
        'fk_user_last_editor' => '4',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '300',
            'height' => '250',
        ],
        'slug' => 'publicidad-opinion-inner-column-pos3',
        'favorite' => '0',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '159',
        'fk_content_type' => '2',
        'fk_author' => '4',
        'urn_source' => '',
        'pk_fk_content' => '159',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
    50 => [
        'map' => null,
        'pk_advertisement' => '238',
        'type_advertisement' => '704',
        'fk_content_categories' => [ 0 => '4' ],
        'img' => '',
        'path' => '',
        'url' => 'http://www.opennemas.com',
        'type_medida' => 'null',
        'num_clic' => '0',
        'num_clic_count' => '0',
        'num_view' => '0',
        'overlap' => '0',
        'script' => '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Onm-468x60-robapagina -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:468px;height:60px"
                 data-ad-client="ca-pub-7694073983816204"
                 data-ad-slot="7755935294"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>',
        'with_script' => '1',
        'timeout' => '4',
        'is_flash' => 0,
        'id' => '238',
        'content_type' => '2',
        'content_type_name' => 'advertisement',
        'title' => 'Full banner - Inner Opinion - 468x60 - Openhost Ads - Adsense',
        'description' => '',
        'body' => '',
        'metadata' => 'full,banner,inner,opoinion,468x60,openhost,ads,adsense',
        'starttime' => '2013-04-18 06:05:41',
        'endtime' => '0000-00-00 00:00:00',
        'created' => '2013-04-18 06:05:41',
        'changed' => '2013-04-18 06:05:41',
        'fk_user' => '3',
        'fk_publisher' => '3',
        'fk_user_last_editor' => '3',
        'category' => '4',
        'category_name' => 'opinion',
        'archive' => null,
        'permalink' => '',
        'position' => '2',
        'in_home' => '0',
        'home_pos' => '100',
        'available' => '1',
        'frontpage' => '0',
        'in_litter' => '0',
        'content_status' => '1',
        'params' => [
            'width' => '468',
            'height' => '60',
        ],
        'slug' => 'full-banner-inner-opinion-468x60-openhost-ads',
        'favorite' => '',
        'with_comment' => '1',
        'cache' => null,
        'content_type_l10n_name' => 'Publicidad',
        'pk_content' => '238',
        'fk_content_type' => '2',
        'fk_author' => '3',
        'urn_source' => '',
        'pk_fk_content' => '238',
        'pk_fk_content_category' => '4',
        'catName' => 'opinion',
    ],
]);
