<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-31 at 02:56:38.
 */
class ContentManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Content
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Content;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ContentManager::getContentTypes
     */
    public function testGetContentTypes()
    {
        $contentTypes = \ContentManager::getContentTypes();

        $this->assertTrue(is_array($contentTypes));
        $this->assertEquals($contentTypes[0]['pk_content_type'], 1);
    }

    /**
     * @covers ContentManager::getContentTypeIdFromName
     */
    public function testGetContentTypeIdFromName()
    {
        $contentTypeId = \ContentManager::getContentTypeIdFromName('article');

        $this->assertEquals($contentTypeId, 1);
    }

    /**
     * @covers ContentManager::getContentTypeIdFromName
     */
    public function testGetContentTypeIdFromNameWithInvalidContentTypeName()
    {
        $contentTypeId = \ContentManager::getContentTypeIdFromName('not-existing-type');

        $this->assertEquals($contentTypeId, false);
    }
}
