#!/usr/bin/env php
<?php
set_time_limit(0);

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Console\Application;

$loader = require_once __DIR__.'/../app/bootstrap.php.cache';

// Load the available route collection
$routes = new \Symfony\Component\Routing\RouteCollection();

// Create the request object
$request = Request::createFromGlobals();
$request->setTrustedProxies(array('127.0.0.1'));

require __DIR__.'/../app/container.php';
require __DIR__.'/../config/config.inc.php';

$application = new Application();

// Iterate over all the available command classes and register them into the
// console application
// $basePath = APPLICATION_PATH.'/app/';
$availableCommandClases = glob(SRC_PATH.'*/Command/*');
foreach ($availableCommandClases as $file) {
    $commandClass = str_replace(
        array(SRC_PATH, '.php', '/'),
        array('', '', '\\'),
        $file
    );

    if (class_exists($commandClass)) {
        $application->add(new $commandClass);
    }
}
$application->run();
