<?php
namespace Onm;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-08-13 at 19:27:26.
 */
class ThemeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Theme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->theme = new \Onm\Theme(
            array(
                'name'        => 'Dummy theme',
                'version'     => '1.1',
                'description' => 'Dummy theme description',
                'author'      => 'OpenHost S.L.',
                'author_uri'  => 'http://www.openhost.es',
            )
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->theme = null;
    }

    /**
     * @covers Onm\Theme::__construct
     */
    public function testConstruct()
    {
        $this->theme = new \Onm\Theme(
            array(
                'name'        => 'Dummy theme',
                'version'     => '1.1',
                'description' => 'Dummy theme description',
                'author'      => 'OpenHost S.L.',
                'author_uri'  => 'http://www.openhost.es',
            )
        );

        $this->assertEquals($this->theme->name, 'Dummy theme');
        $this->assertEquals($this->theme->version, '1.1');
        $this->assertEquals($this->theme->description, 'Dummy theme description');
        $this->assertEquals($this->theme->author, 'OpenHost S.L.');
        $this->assertEquals($this->theme->author_uri, 'http://www.openhost.es');
    }
}
