<?php
namespace Framework\Tests\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-31 at 02:56:38.
 */
class ContentManagerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Content
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = $this->getMockBuilder('ServiceContainer')
            ->setMethods([ 'get', 'hasParameter' ])
            ->getMock();

        $this->contentHelper = $this->getMockBuilder('Common\Core\Component\Helper\ContentHelper')
            ->disableOriginalConstructor()
            ->setMethods(['isInTime'])
            ->getMock();

        $this->kernel = $this->getMockBuilder('Kernel')
            ->setMethods([ 'getContainer' ])
            ->getMock();

        $this->cache = $this->getMockBuilder('Cache')
            ->setMethods([ 'fetch' ])
            ->getMock();

        $this->locale = $this->getMockBuilder('Common\Core\Component\Locale\Locale')
            ->disableOriginalConstructor()
            ->setMethods([ 'getTimeZone' ])
            ->getMock();

        $this->container->expects($this->any())->method('get')
            ->will($this->returnCallback([ $this, 'serviceContainerCallback' ]));
        $this->kernel->expects($this->any())->method('getContainer')
            ->willReturn($this->container);
        $this->locale->expects($this->any())->method('getTimeZone')
            ->willReturn(new \DateTimeZone('UTC'));

        $GLOBALS['kernel'] = $this->kernel;

        $this->object = new \Content;
    }

    public function serviceContainerCallback($name)
    {
        switch ($name) {
            case 'cache':
                return $this->cache;

            case 'core.helper.content':
                return $this->contentHelper;

            case 'core.locale':
                return $this->locale;
        }

        return null;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ContentManager::getContentTypes
     */
    public function testGetContentTypes()
    {
        $contentTypes = \ContentManager::getContentTypes();

        $this->assertTrue(is_array($contentTypes));
        $this->assertEquals($contentTypes[0]['pk_content_type'], 1);
    }

    /**
     * @covers ContentManager::getContentTypeIdFromName
     */
    public function testGetContentTypeIdFromName()
    {
        $contentTypeId = \ContentManager::getContentTypeIdFromName('article');

        $this->assertEquals($contentTypeId, 1);
    }

    /**
     * @covers ContentManager::getContentTypeIdFromName
     */
    public function testGetContentTypeIdFromNameWithInvalidContentTypeName()
    {
        $contentTypeId = \ContentManager::getContentTypeIdFromName('not-existing-type');

        $this->assertEquals($contentTypeId, false);
    }

    /**
     * @covers ContentManager::getEarlierStarttimeOfScheduledContents
     */
    public function testGetEarlierStarttimeOfScheduledContents()
    {
        $contents = [];
        $expires  = \ContentManager::getEarlierStarttimeOfScheduledContents($contents);

        $this->assertEquals($expires, false);
    }

    /**
     * @covers ContentManager::getInTime
     */
    public function testGetInTime()
    {
        $rc = new \ReflectionClass('ContentManager');
        $cm = $rc->newInstanceWithoutConstructor();

        // Check with content in time
        $content            = new \Content();
        $content->starttime = '2012-08-22 03:03:12';
        $content->endtime   = '3012-08-27 03:03:12';

        $this->contentHelper->expects($this->at(0))->method('isInTime')
            ->willReturn(true);
        $this->contentHelper->expects($this->at(1))->method('isInTime')
            ->willReturn(false);
        $this->contentHelper->expects($this->at(2))->method('isInTime')
            ->willReturn(false);
        $this->contentHelper->expects($this->at(3))->method('isInTime')
            ->willReturn(false);
        $this->contentHelper->expects($this->at(4))->method('isInTime')
            ->willReturn(true);
        $this->contentHelper->expects($this->at(5))->method('isInTime')
            ->willReturn(false);

        $this->assertEquals(1, count($cm->getinTime([ $content ])));

        // Check with content with scheduling incorrent (start = end)
        $content->starttime = '2012-08-22 03:03:12';
        $content->endtime   = '2012-08-22 03:03:12';

        $this->assertEquals(0, count($cm->getinTime([ $content ])));

        // Check with content scheduled in the future
        $content->starttime = '3059-08-22 03:03:12';
        $content->endtime   = '3059-08-23 03:03:12';

        $this->assertEquals(0, count($cm->getinTime([ $content ])));

        // Check with content dued in the past
        $content->starttime = '2010-08-22 03:03:12';
        $content->endtime   = '2010-08-23 03:03:12';

        $this->assertEquals(0, count($cm->getinTime([ $content ])));

        // Check with content with null values
        $content->starttime = null;
        $content->endtime   = null;

        $this->assertEquals(1, count($cm->getinTime([ $content ])));

        // Check with content with zeroed values
        $content->starttime = '0000-00-00 00:00:00';
        $content->endtime   = '0000-00-00 00:00:00';

        $this->assertEquals(0, count($cm->getinTime([ $content ])));
    }
}
