<table style="padding:10px;">
    <tr style="width:40%">
        <td><strong>Youtube</strong></td>
        <td>http://www.youtube.com</td>
    </tr>
    <tr>
        <td><strong>Vimeo</strong></td>
        <td>http://vimeo.com</td>
    </tr>
    <tr>
        <td><strong>Metacafe</strong></td>
        <td>http://metacafe.com</td>
    </tr>
    <tr>
        <td><strong>Dailymotion</strong></td>
        <td>http://dailymotion.com</td>
    </tr>
    <tr>
        <td><strong>Collegehumor</strong></td>
        <td>http://collegehumor.com</td>
    </tr>
    <tr>
        <td><strong>Blip.tv</strong></td>
        <td>http://blip.tv</td>
    </tr>
    <tr>
        <td><strong>Myspace</strong></td>
        <td>http://vids.myspace.com</td>
    </tr>
    <tr>
        <td><strong>Ted Talks</strong></td>
        <td>http://www.ted.com/talks</td>
    </tr>
    <tr>
        <td><strong>11870.com</strong></td>
        <td>http://11870.com</td>
    </tr>
    <tr>
        <td><strong>Marca.tv</strong></td>
        <td>http://www.marca.tv</td>
    </tr>
    <tr>
        <td><strong>Dalealplay</strong></td>
        <td>http://www.dalealplay.com</td>
    </tr>
    <tr>
        <td><strong>Rutube</strong></td>
        <td>http://www.rutube.ru</td>
    </tr>
</table>