<?php
namespace DefaultBundle\Controller;

// require_once '/home/fran/Projects/OpenHost/onm-framework/app/bundles/DefaultBundle/Controller/ErrorController.php';

/**
 * Test class for ErrorController.
 * Generated by PHPUnit on 2011-12-26 at 07:23:46.
 */
class DummyUnitTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new ErrorController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Content::isInTime2
     * @todo Implement testNotFoundAction().
     */
    public function testFranisHandsome()
    {
        // $article = \Article::isInTime2('-1 day');
        // $article = new \Article('');
        // $this->assertTrue(true, 'Fran is handsome');
    }

    /**
     * Test double
     *
     * @return void
     **/
    public function testArticleClass()
    {
        // Create a stub for the SomeClass class.
        $stub = $this->getMock('Article');

        // Configure the stub.
        $stub->expects($this->any())
             ->method('create')
             ->will($this->returnValue('foo'));

        // Calling $stub->doSomething() will now return
        // 'foo'.
        $this->assertEquals('foo', $stub->create('as'));
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testErrorAction().
     */
    // public function testErrorAction()
    // {
    //     // Remove the following lines when you implement this test.
    //     $this->markTestIncomplete(
    //       'This test has not been implemented yet.'
    //     );
    // }
}
