<?php
/*
 * This file is part of the Onm package.
 *
 * (c) Openhost, S.L. <developers@openhost.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Common\NewsAgency\Component\Parser\Nitf;

/**
 * Parses XML files in custom NITF format for EFE.
 */
class NitfOpennemas extends Nitf
{
    /**
     * {@inheritdoc}
     */
    public function checkFormat($data)
    {
        return parent::checkFormat($data) && $this->isOpennemasNitf($data);
    }

    /**
     * {@inheritdoc}
     */
    public function getAgencyName($data)
    {
        $agency = $data->xpath('//rights/rights.agent');

        if (!empty($agency) && !empty($agency[0])) {
            return (string) $agency[0];
        }

        return null;
    }

    /**
     * Returns the body from the parsed data.
     *
     * @param SimpleXMLObject The parsed data.
     *
     * @return string The body.
     */
    public function getBody($data)
    {
        $bodies = $data->xpath('//body/body.content');

        if (empty($bodies)) {
            return '';
        }

        $body = '';
        if (!empty((string) $bodies[0])) {
            $body = preg_replace(
                ["/\n/", '/<p>\s*<\/p>/'],
                ['', ''],
                html_entity_decode((string) $bodies[0])
            );
        }

        return iconv(mb_detect_encoding($body), "UTF-8", $body);
    }

    /**
     * {@inheritdoc}
     */
    public function getTags($data)
    {
        $tags = $data->xpath('//head/docdata/key-list/keyword');

        if (!empty($tags)) {
            return (string) $tags[0]->attributes()->{'key'};
        }

        return '';
    }

    /**
     * {@inheritdoc}
     */
    public function parse($data)
    {
        $resource = parent::parse($data);

        $resource->author       = $this->getAuthor($data);
        $resource->author_photo = $this->getAuthorPhoto($data);
        $resource->isChild      = !empty($this->getParentId($data));
        $resource->uid          = $this->getUid($data);

        return $resource;
    }

    /**
     * Returns the author data for the current resource.
     *
     * @param SimpleXMLObject $data The data to parse.
     *
     * @return array The author data.
     */
    protected function getAuthor($data)
    {
        $author = $data->xpath('//rights/rights.owner');

        if (!empty($author) && !empty($author[0])) {
            return (string) $author[0];
        }

        return null;
    }

    /**
     * Returns the author photo URL.
     *
     * @param SimpleXMLObject $data The data to parse.
     *
     * @return string The author photo URL.
     */
    protected function getAuthorPhoto($data)
    {
        $photo = $data->xpath('//rights/rights.owner.photo');

        if (!empty($photo)) {
            return (string) $photo[0];
        }

        return null;
    }

    /**
     * Returns the id of the parent content.
     *
     * @param SimpleXMLObject The parsed data.
     *
     * @return string The parent content id.
     */
    public function getParentId($data)
    {
        $id = $data->xpath('//doc-parent');

        if (empty($id)) {
            return '';
        }

        $value = (string) $id[0];

        if (!empty($id[0]->attributes())
            && !empty($id[0]->attributes()->{'id-string'})
        ) {
            $value = (string) $id[0]->attributes()->{'id-string'}[0];
        }

        return $value;
    }

    /**
     * Returns the uid from the parsed data.
     *
     * @param SimpleXMLObject The parsed data.
     *
     * @return string The uid.
     */
    public function getUid($data)
    {
        $uid = $data->xpath('//doc-uid');

        if (empty($uid)) {
            return '';
        }

        $value = (string) $uid[0];

        if (!empty($uid[0]->attributes())
            && !empty($uid[0]->attributes()->{'id-string'})
        ) {
            $value = (string) $uid[0]->attributes()->{'id-string'}[0];
        }

        return $value;
    }

    /**
     * Checks if the NITF provided was generated by Opennemas.
     *
     * @param SimpleXMLObject $data The data to parse.
     *
     * @return bool True if the NITF was generated by Opennemas. False
     *              otherwise.
     */
    protected function isOpennemasNitf($data)
    {
        $agent = $data->xpath('//doc.rights/@agent');

        if (!empty($agent)) {
            return (string) $agent[0] === 'Opennemas';
        }

        return false;
    }
}
