{extends file="layout.tpl"}

{block name="head-js"}
<!-- Generated by OpenX 2.8.5 -->
<script type='text/javascript' src='http://localhost/openx-2.8.5/www/delivery/spcjs.php?id=1'></script>
{/block}

{block name="body-content"}

    {* foreach item=zone from=$zones}
    <h1>{$zone.zoneName}</h1>
    <div>{$zone|var_dump}</div>
    <div id="{$zone.zoneId}">
        <script type='text/javascript'><!--// <![CDATA[
        OA_show({$zone.zoneId});
        // ]]> --></script>
    </div>
    {/foreach *}

    {foreach item=banner from=$banners}
    <div id="id">
        {$banner}
    </div>    
    {/foreach}

{* <div>{$banner}</div> *}


{/block}