<?php
namespace DefaultBundle\Controller;


// require_once '/home/fran/Projects/OpenHost/onm-framework/app/bundles/DefaultBundle/Controller/ErrorController.php';

/**
 * Test class for ErrorController.
 * Generated by PHPUnit on 2011-12-26 at 07:23:46.
 */
class DummyTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new ErrorController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testNotFoundAction().
     */
    public function testFranisHandsome()
    {
        $this->assertTrue(true, 'Fran is handsome');
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testErrorAction().
     */
    // public function testErrorAction()
    // {
    //     // Remove the following lines when you implement this test.
    //     $this->markTestIncomplete(
    //       'This test has not been implemented yet.'
    //     );
    // }
}
?>
