<?php
namespace Onm\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-31 at 02:16:43.
 */
class VersionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Version
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Version;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     **/
    public function testVersionIsANumberedFormatedVersion()
    {
        preg_match('@(\d\.?){2,}@', Version::VERSION, $matches);
        $this->assertTrue(count($matches) > 0);
    }

    /**
     * @covers Onm\Common\Version::compare
     */
    public function testCompareShouldReturnFalseIsCurrentVersionisLewer()
    {
        $this->assertEquals(-1, $this->object->compare(0));
    }

    /**
     * @covers Onm\Common\Version::compare
     */
    public function testCompareShouldReturnTrueIsCurrentVersionisBigger()
    {
        $this->assertEquals(1, $this->object->compare(10000));
    }

        /**
     * @covers Onm\Common\Version::compare
     */
    public function testCompareShouldReturnTrueIsCurrentVersionisEqualCompared()
    {
        $version = Version::VERSION;
        $this->assertEquals(0, $this->object->compare($version));
    }
}
