{javascripts
    src="@Common/js/libs/moment-with-langs.min.js,
        @Common/js/libs/moment-timezone.min.js,
        @Common/js/libs/moment-data.js,
        @Common/js/libs/messenger.min.js,
        @FosJsRoutingBundle/js/router.js,
        @Common/js/routes.js,
        @BackendBundle/lib/angular.min.js,
        @BackendBundle/lib/angular-translate.min.js,
        @BackendBundle/lib/ui-sortable.js,
        @BackendBundle/lib/ui-bootstrap-tpls-0.10.0.min.js,
        @BackendBundle/js/app.js,
        @BackendBundle/js/controllers.js,
        @BackendBundle/js/services.js,
        @BackendBundle/js/filters.js,
        @BackendBundle/js/directives.js,
        @BackendBundle/js/controllers/*,
        @BackendBundle/js/services/*,
        @BackendBundle/js/filters/*,
        @BackendBundle/js/directives/*"
    }
    <script type="text/javascript" src="{$asset_url}"></script>
{/javascripts}
